server:
  port: 8084

spring:
  application:
    name: tracking-service

  # Configuración Redis
  data:
    redis:
      host: localhost
      port: 6379

  # Configuración OAuth2 Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

# Configuración de logging
logging:
  level:
    com.proyecto.trackingservice: DEBUG
    org.springframework.security: DEBUG

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
# Perfil para Docker
spring:
  config:
    activate:
      on-profile: docker

  data:
    redis:
      host: redis-tracking
      port: 6379

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/oauth2/jwks

server:
  port: 8084
