
spring:
  application:
    name: gateway
  security:
    user:
      enabled: false
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
        - id: cliente-service
          uri: http://cliente-service:8082
          predicates:
            - Path=/api/clientes/**
        - id: pedido-service
          uri: http://pedido-service:8083
          predicates:
            - Path=/api/pedidos/**
        - id: tracking-service
          uri: http://tracking-service:8084
          predicates:
            - Path=/api/tracking/**

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

server:
  port: 9001
