# Configuración del Pedido Service
server:
  port: 8083

spring:
  application:
    name: pedido-service
  
  # Configuración MySQL Database
  datasource:
    url: jdbc:mysql://localhost:3307/pedido_db
    username: pedido_user
    password: pedido_pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # Configuración JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    
  # Configuración OAuth2 Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

# Configuración de logging
logging:
  level:
    com.proyecto.pedidoservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Configuración de Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Configuración de OpenAPI/Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

# Configuración de tracking service
tracking:
  service:
    url: http://localhost:8084/api/tracking/update
    base:
      url: http://localhost:8084

# Configuración de cliente service
cliente:
  service:
    url: http://localhost:8082
    
---

# Perfil para Docker
spring:
  config:
    activate:
      on-profile: docker
      
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://mysql-db:3306/pedido_db}
    username: ${DATABASE_USERNAME:pedido_user}
    password: ${DATABASE_PASSWORD:pedido_pass}
    
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVICE_URL:http://auth-service:8081}/oauth2/jwks

server:
  port: ${SERVER_PORT:8083}

# Configuración de tracking service para Docker
tracking:
  service:
    url: ${TRACKING_SERVICE_URL:http://tracking-service:8084}/api/tracking/update
    base:
      url: ${TRACKING_SERVICE_URL:http://tracking-service:8084}

# Configuración de cliente service para Docker
cliente:
  service:
    url: ${CLIENTE_SERVICE_URL:http://cliente-service:8082}