server:
  port: 9001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8081
          predicates:
            - Path=/api/auth/**
        - id: cliente-service
          uri: http://cliente-service:8082
          predicates:
            - Path=/api/clientes/**
        - id: pedido-service
          uri: http://pedido-service:8083
          predicates:
            - Path=/api/pedidos/**
        - id: tracking-service
          uri: http://tracking-service:8084
          predicates:
            - Path=/api/tracking/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  logging:
    level:
      org.springframework.cloud.gateway: DEBUG
      org.springframework.web.reactive: DEBUG
      reactor.netty.http.client: DEBUG
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://auth-service:8081/oauth2/jwks
